//  StockCatalog.swift — the film and paper library, read from the bundle.
//
//  `Resources/StockCatalog.json` is generated by `Tools/gen-catalog.py` from
//  the engine's profile directory, so the picker cannot list a stock the
//  engine does not have. Regenerate it when a profile is added.

import Foundation

struct Stock: Codable, Identifiable, Hashable, Sendable {
    let id: String
    let name: String
    let stage: String          // "filming" | "printing"
    let use: String            // "still" | "cine"
    let type: String?
    let targetPrint: String?
    let hasPreviewLUT: Bool
    let pairedFilm: String?
    let cover: String?

    var isFilm: Bool { stage == "filming" }
    var isPaper: Bool { stage == "printing" }
    var isCine: Bool { use == "cine" }
    var brand: String { name.split(separator: " ").first.map(String.init) ?? "" }
    var coverURL: URL? {
        cover.flatMap { StockCatalog.bundle.url(forResource: $0, withExtension: nil, subdirectory: "Resources/FilmCovers") }
    }
}

struct StockCatalog: Sendable {
    let stocks: [Stock]

    /// The bundle that carries Resources/: the app, or the test bundle.
    static var bundle: Bundle { Bundle(for: BundleToken.self) }
    private final class BundleToken {}

    static let shared: StockCatalog = {
        let url = bundle.url(forResource: "StockCatalog", withExtension: "json", subdirectory: "Resources")
        if let url, let data = try? Data(contentsOf: url),
           let decoded = try? JSONDecoder().decode(Wrapper.self, from: data) {
            return StockCatalog(stocks: decoded.stocks)
        }
        return StockCatalog(stocks: [])
    }()

    private struct Wrapper: Decodable { let stocks: [Stock] }

    var films: [Stock] { stocks.filter(\.isFilm) }
    var papers: [Stock] { stocks.filter(\.isPaper) }
    func stock(_ id: String) -> Stock? { stocks.first { $0.id == id } }

    /// Films in the order the picker shows them: still first, brand-grouped,
    /// then cine. Within a brand the order is the catalog's (alphabetical).
    var filmsForPicker: [Stock] {
        let still = films.filter { !$0.isCine }
        let cine = films.filter(\.isCine)
        return still + cine
    }

    /// Papers grouped for the picker: Still, then Cine.
    var paperGroups: [(title: String, papers: [Stock])] {
        [("Still", papers.filter { !$0.isCine }), ("Cine", papers.filter(\.isCine))]
    }

    /// Whether `paper` is the declared target of `film` — an honest pairing
    /// versus an approximation (API-SPEC §2's pairing note).
    func isDeclaredPairing(film: String, paper: String) -> Bool {
        stock(film)?.targetPrint == paper
    }
}
